name: Test Site Monitor

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]
  schedule:
    # Run tests weekly
    - cron: '0 0 * * 0'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-version: ['7.4', '8.0', '8.1', '8.2']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: curl
        
    - name: Validate PHP syntax
      run: php -l index.php
      
    - name: Check for syntax errors
      run: |
        # Check for common PHP issues
        php -l index.php
        echo "✅ PHP syntax is valid"
        
    - name: Test environment loading
      run: |
        # Test .env file loading
        cat > .env << EOF
        MONITOR_1_NAME="Test Site"
        MONITOR_1_URL="https://httpbin.org/status/200"
        MONITOR_1_WEBHOOK="https://discord.com/api/webhooks/test"
        MONITOR_1_KEY="test_site"
        EOF
        
        # Test that the script can load the .env file
        php -r "
        require_once 'index.php';
        \$env = loadEnv();
        \$sites = extractSiteConfigs(\$env);
        echo '✅ Loaded ' . count(\$sites) . ' sites from .env\n';
        "
        
    - name: Test curl functionality
      run: |
        # Test that cURL is available and working
        php -r "
        if (function_exists('curl_init')) {
            echo '✅ cURL extension is available\n';
        } else {
            echo '❌ cURL extension is not available\n';
            exit(1);
        }
        "
        
    - name: Test log directory creation
      run: |
        # Test log directory creation functionality
        php -r "
        require_once 'index.php';
        writeLog('test_key', 'Test log entry');
        if (is_dir('logs/test_key')) {
            echo '✅ Log directory creation works\n';
        } else {
            echo '❌ Log directory creation failed\n';
            exit(1);
        }
        "
        
    - name: Cleanup test files
      run: |
        rm -rf logs/
        rm -f .env 